[build]
command = "pnpm run build" # Replace with your build command
publish = "/apps/client/dist" # Replace with the path to your React app's build directory

[build.environment]
# Add any environment variables required for your application
DATABASE_URI=mongodb+srv://a01141399246:Xo36ez4kqeo5VAu9@cluster0.h26ag7w.mongodb.net/
JWT_SECRET=dta545kdgf76gsfg5hfds3sjavcascjkkjfetyjgevt48onvlhklv4gvaru5


